spring.application.name=user-service


spring.datasource.url=jdbc:postgresql://localhost:5432/db_ecomarket
spring.datasource.username=postgres
spring.datasource.password=Vicente5150.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html


server.port=8081
